import MoreVertIcon from "@mui/icons-material/MoreVert";
import img1 from "./images/Userinfosys.svg";
import img2 from "./images/Userwipro.svg";
import img3 from "./images/Useracc.svg";
import img4 from "./images/Userfafa.svg";
import img5 from "./images/BGloudha.svg";
import img6 from "./images/Userfakfa.svg";
import img7 from "./images/UserHCL.svg";
import img8 from "./images/BGRedington.svg";
import img9 from "./images/UserMphasis.svg";
import img10 from "./images/UserLandT.svg";

export const tablearray = [
  {
    id: 1,
    image: img1,
    name: "Infosys",
    email: "management@infosys.com",
    phone: +919563214587,
    contPerson: "Vijayent Roy",
    facilitator: "--",
    sites: 12,
    tenants: "--",
    tenantgroups: "--",
    action: <MoreVertIcon />,
    actionShow: false,
  },
  {
    id: 2,
    image: img2,
    name: "Wipro",
    email: "management@wipro.com",
    phone: +918732654789,
    contPerson: "Kalpit Soni",
    facilitator: "--",
    sites: 8,
    tenants: "--",
    tenantgroups: "--",
    action: <MoreVertIcon />,
    actionShow: false,
  },
  {
    id: 3,
    image: img3,
    name: "Accenture",
    email: "management@accenture.com",
    phone: +918732654789,
    contPerson: "Drishti Sane",
    facilitator: "--",
    sites: 4,
    tenants: "--",
    tenantgroups: "--",
    action: <MoreVertIcon />,
    actionShow: false,
  },
  {
    id: 4,
    image: img4,
    name: "Capgemini",
    email: "management@capgemini.com",
    phone: +918432657995,
    contPerson: "Aisha Keer ",
    facilitator: "--",
    sites: 6,
    tenants: "--",
    tenantgroups: "--",
    action: <MoreVertIcon />,
    actionShow: false,
  },
  {
    id: 5,
    image: img5,
    name: "Louha",
    email: "management@lodha.com",
    phone: +919642357894,
    contPerson: "Kanika Khare",
    facilitator: "--",
    sites: 24,
    tenants: "--",
    tenantgroups: "--",
    action: <MoreVertIcon />,
    actionShow: false,
  },
  {
    id: 6,
    image: img6,
    name: "Tata Consultancy Services",
    email: "management@tcs.com",
    phone: +919632457468,
    contPerson: "Prabhat Rao",
    facilitator: "--",
    sites: 10,
    tenants: "--",
    tenantgroups: "--",
    action: <MoreVertIcon />,
    actionShow: false,
  },
  {
    id: 7,
    image: img7,
    name: "HCL",
    email: "management@hcl.com",
    phone: +919452136487,
    contPerson: "Venkat Pant",
    facilitator: "--",
    sites: 5,
    tenants: "--",
    tenantgroups: "--",
    action: <MoreVertIcon />,
    actionShow: false,
  },
  {
    id: 8,
    image: img8,
    name: "Redington",
    email: "management@redington.com",
    phone: +919326571865,
    contPerson: "Samir Yadav",
    facilitator: "--",
    sites: 1,
    tenants: "--",
    tenantgroups: "--",
    action: <MoreVertIcon />,
    actionShow: false,
  },
  {
    id: 9,
    image: img9,
    name: "Mphasis",
    email: "management@mphasis.com",
    phone: +919874621547,
    contPerson: "Sweta Chawla",
    facilitator: "--",
    sites: 1,
    tenants: "--",
    tenantgroups: "--",
    action: <MoreVertIcon />,
    actionShow: false,
  },
  {
    id: 10,
    image: img10,
    name: "Larsen & Toubro",
    email: "management@larsentoubro.com",
    phone: +919874621547,
    contPerson: "Abhishek Kumar",
    facilitator: "--",
    sites: 16,
    tenants: "--",
    tenantgroups: "--",
    action: <MoreVertIcon />,
    actionShow: false,
  },
];
